#!/bin/sh

cd /manage-this-node

if [ ! -e /config/config.json ]; then
    cp /manage-this-node/config.json.template /config/config.json
fi

ln -sf /config/config.json /manage-this-node/config.json

mkdir -p /config
chown -R ${UID}:${GID} /config /manage-this-node

if [ $# == 0 ]; then
    exec su-exec ${UID}:${GID} /sbin/tini -- npm start
else
    exec su-exec ${UID}:${GID} /sbin/tini -- "$@"
fi